spring:
  application:
    name: login
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

security:
  expires-at: 3600
  key:
    public: ${PUBLIC_KEY}
    private: ${PRIVATE_KEY}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.filter: DEBUG
    org.springframework.security.authentication: DEBUG

